### ISSUE TITLE
[P3] - Leaderboard size is unbalanced

### ISSUE THREAD

**Issue by vaiolis** [arnavnc/member-rec#12]
On desktop, the leaderboard's height is not balanced compared to the instructions panel on the left side. We can address this issue by limiting the number of leaderboard entries shown to 10. We may also want to filter out unimpressive leaderboard entries and show a placeholder when there aren't enough entries to fill out a top 10.

**Comment by arnavnc** [comment]
Limited to ten, will fill up the entries to ten to make it impressive!
