### ISSUE TITLE
Post-game Results page should be rendered via React router

### ISSUE THREAD

**Issue by vaiolis** [arnavnc/member-rec#6]
Following https://github.com/arnavnc/member-rec/commit/a5cbda55b4e1be6f370646f053dd15d4bfecbc24#r82650145, I've opened this issue to track the refactor work needed to support URL parameters for the `/results` route which will both allow the results page to be directly URL addressable (which can help implement share via social functionality) and will more appropriately implement the results screen that is shown after the player finishes a game.

Link to React Router documentation for URL parameters: https://v5.reactrouter.com/web/example/url-params

**Comment by arnavnc** [comment]
Added params using useLocation hook in the results page. Not fully what you were going for, but that will be addressable in a separate issue concerning social functionality.
